#!/usr/bin/env python
# flake8: noqa

"""Bootstrap script."""

if __name__ == "__main__":
    from runner.engine.cli import main
    import runner

    try:
        main()
    except SystemExit as ex:
        if ex.code != 0:
            raise
