logging:
  version: 1
  formatters:
    simple:
      format: '%(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: DEBUG
      formatter: simple
  loggers:
    '':
      level: INFO
    runner:
      level: DEBUG
    gamma:
      level: DEBUG
    dirsync:
      level: WARN
    azure:
      level: WARN
  root:
    level: INFO
    handlers: [console]
